### ISSUE TITLE
水波图有对wx适配的uniapp版本吗？

### ISSUE THREAD

**Issue by nevergoneok** [Zhuyi731/echarts-for-wx-uniapp#1]
如题，想在uniapp中使用水波图，但是wx不展示

**Comment by Zhuyi731** [comment]
是水球图吧，你是不是没有装水球图的插件  
[插件地址](https://github.com/ecomfe/echarts-liquidfill)

**Comment by Zhuyi731** [comment]
> 如题，想在uniapp中使用水波图，但是wx不展示

是水球图吧，你是不是没有装水球图的插件
插件地址
