### ISSUE TITLE
后台获取的数据再渲染到option中 数据变了但是图表没变化 该怎么解决

### ISSUE THREAD

**Issue by xiaozhang121** [Zhuyi731/echarts-for-wx-uniapp#11]
你好 将后台获取的数据再渲染到option中 数据变了但是图表没变化 该怎么解决

**Comment by Zhuyi731** [comment]
能提供一下代码吗？

**Comment by xiaozhang121** [comment]
类似这样的:this.ec.option.xAxis[0].data = [1,2,3,4,5];
然后输出的时候this.ec.option.xAxis[0].data也确实变了 但是图表没有数据 需要通过setoption再渲染一次数据吗?

**Comment by Zhuyi731** [comment]
不用啊，你确定最开始渲染成功了吗

**Comment by xiaozhang121** [comment]
确定的 就是第一次渲染图表没有数据个架子 但是加入给这个echart标签加个v-if 然后再通过点击事件来控制这个图表隐藏显示的话 再点击显示的时候数据就可以渲染上去

**Comment by xiaozhang121** [comment]
确定的 就是第一次渲染的时候 只有个架子没有数据 但是如果通过点击事件 v-if来进行显示隐藏的话 点击之后显示 数据就可以渲染上去了

**Comment by xiaozhang121** [comment]
确定的 就是第一次渲染的时候 只有个架子没有数据 但是如果通过点击事件 v-if来对echart标签进行显示隐藏的话 点击之后显示 数据就可以渲染上去了

**Comment by Zhuyi731** [comment]
这种情况我好像还没遇到过

**Comment by Zhuyi731** [comment]
你可以试试用display:none  block 来控制显示隐藏    或者用setOption重新渲染下

**Comment by xiaozhang121** [comment]
setOption需要DOM节点 但是我通过输出这个this.$refs['uni-ec-canvas'].$curChart是undefined是为什么...

**Comment by Zhuyi731** [comment]
因为之前别人的pr导致了这个bug，你可以根据这个[issue](https://github.com/Zhuyi731/echarts-for-wx-uniapp/issues/10)先改下。我还没来得及改

**Comment by xiaozhang121** [comment]
我还是个新手 哭了@_@

**Comment by xiaozhang121** [comment]
那请问还有什么方式可以重新渲染吗

**Comment by Zhuyi731** [comment]
你重新更新下uni-ec-canvas.js那个文件，我修改了一下，可以获取到$curChart了

**Comment by xiaozhang121** [comment]
好的 我试试 真是麻烦你了

**Comment by xiaozhang121** [comment]
问题解决了 谢谢你了

**Comment by Zhuyi731** [comment]
不用客气
