### ISSUE TITLE
关于 uni+ts 开发引入组件报错问题

### ISSUE THREAD

**Issue by lz-web** [Zhuyi731/echarts-for-wx-uniapp#13]
![image](https://user-images.githubusercontent.com/55732016/84562141-c627b200-ad84-11ea-8e60-4c040b8ff71a.png)

你好，就是正常第一步，import 引用组件报此类错误，请问怎么处理

**Comment by Zhuyi731** [comment]
> ![image](https://user-images.githubusercontent.com/55732016/84562141-c627b200-ad84-11ea-8e60-4c040b8ff71a.png)
> 
> 你好，就是正常第一步，import 引用组件报此类错误，请问怎么处理

能发一下示例代码和报错的信息吗

**Comment by Zhuyi731** [comment]
> ![image](https://user-images.githubusercontent.com/55732016/84562141-c627b200-ad84-11ea-8e60-4c040b8ff71a.png)
> 
> 你好，就是正常第一步，import 引用组件报此类错误，请问怎么处理

你这里引入的路径错了呀，  应该是./uni-ec-canvas/uni-ec-canvas.vue
而不是 ./uni-ec-canvas/ec-canvas.vue
