### ISSUE TITLE
请问这个可以引入地图么？

### ISSUE THREAD

**Issue by ghostsGod** [Zhuyi731/echarts-for-wx-uniapp#14]

**Comment by Zhuyi731** [comment]
> _No description provided._

可以的

**Comment by ghostsGod** [comment]
那想请教您一下，要以什么方式引入呢？我试了uni-ec-canvas组件中的initChart方法中加入echarts.registerMap('china', china);，但是uni-app没有展示成功，china.js用的是module.exports=地图网站下载的json信息。是我使用的方法不对么，还是china.js有什么要求

**Comment by Zhuyi731** [comment]
可以看下这个issue的使用  [地图issue](https://github.com/Zhuyi731/echarts-for-wx-uniapp/issues/9)

**Comment by Zhuyi731** [comment]
> 那想请教您一下，要以什么方式引入呢？我试了uni-ec-canvas组件中的initChart方法中加入echarts.registerMap('china', china);，但是uni-app没有展示成功，china.js用的是module.exports=地图网站下载的json信息。是我使用的方法不对么，还是china.js有什么要求

看下是不是同样的问题  echart必须使用组件的echart

**Comment by ghostsGod** [comment]
我用那哥们的方法试了一下，会有报错
_china.default.registerMap is not a function
我用您这插件是直接在uniapp插件市场导入的，引入的china.js和china.json也是在其他项目里找的，在码云里的一个项目找的
![image](https://user-images.githubusercontent.com/24351755/87026593-87afd680-c20e-11ea-9885-6ca91156f09f.png)
是js版本有误差导致的么？

**Comment by ghostsGod** [comment]
`<template>
  <view class="mapWrapper">
    <uni-ec-canvas
      class="customMap"
      id="customMap"
      canvas-id="customMapCharts"
      ref="customMap"
      :ec="ec"
    ></uni-ec-canvas>
  </view>
</template>

<script>
import '../../static/js/china.js' 
import china from '@/js_sdk/yanhao-echarts-for-wx/uni-ec-canvas/china.json'
import echart from '@/js_sdk/yanhao-echarts-for-wx/uni-ec-canvas/echarts.js'
import uniEcCanvas from '@/js_sdk/yanhao-echarts-for-wx/uni-ec-canvas/uni-ec-canvas';

echart.registerMap('china', china)

function randomData() {  
     return Math.round(Math.random()*500);  
} 
var mydata = [  
    {name: '北京',value: '100' },{name: '天津',value: randomData() },  
    {name: '上海',value: randomData() },{name: '重庆',value: randomData() },  
    {name: '河北',value: randomData() },{name: '河南',value: randomData() },  
    {name: '云南',value: randomData() },{name: '辽宁',value: randomData() },  
    {name: '黑龙江',value: randomData() },{name: '湖南',value: randomData() },  
    {name: '安徽',value: randomData() },{name: '山东',value: randomData() },  
    {name: '新疆',value: randomData() },{name: '江苏',value: randomData() },  
    {name: '浙江',value: randomData() },{name: '江西',value: randomData() },  
    {name: '湖北',value: randomData() },{name: '广西',value: randomData() },  
    {name: '甘肃',value: randomData() },{name: '山西',value: randomData() },  
    {name: '内蒙古',value: randomData() },{name: '陕西',value: randomData() },  
    {name: '吉林',value: randomData() },{name: '福建',value: randomData() },  
    {name: '贵州',value: randomData() },{name: '广东',value: randomData() },  
    {name: '青海',value: randomData() },{name: '西藏',value: randomData() },  
    {name: '四川',value: randomData() },{name: '宁夏',value: randomData() },  
    {name: '海南',value: randomData() },{name: '台湾',value: randomData() },  
    {name: '香港',value: randomData() },{name: '澳门',value: randomData() }  
];

export default {
    data() {
        return {
            ec: {
                option: {
                backgroundColor: '#FFFFFF',  
                title: {  
                    text: '全国地图大数据',  
                    subtext: '',  
                    x:'center'  
                },  
                tooltip : {  
                    trigger: 'item'  
                },  
                
                //左侧小导航图标
                visualMap: {  
                    show : true,  
                    x: 'left',  
                    y: 'center',  
                    splitList: [   
                        {start: 500, end:600},{start: 400, end: 500},  
                        {start: 300, end: 400},{start: 200, end: 300},  
                        {start: 100, end: 200},{start: 0, end: 100},  
                    ],  
                    color: ['#5475f5', '#9feaa5', '#85daef','#74e2ca', '#e6ac53', '#9fb5ea']  
                },  
                
                //配置属性
                series: [{  
                    name: '数据',  
                    type: 'map',  
                    mapType: 'china',   
                    roam: true,  
                    label: {  
                        normal: {  
                            show: true  //省份名称  
                        },  
                        emphasis: {  
                            show: false  
                        }  
                    },  
                    data:mydata  //数据
                }]                    
                }
            }
        }
    },

    // mounted() {
    //    this.$refs.customMap.$curChart.setOption(this.ec.option)
    // },

    components: {
        uniEcCanvas
    }
}

</script>

<style>
.mapWrapper {
    height: 400px;
    widows: 350px;
}
    .customMap {
        height: 385px;
        width: 350px;
        display: block;
    }
</style>
`

**Comment by ghostsGod** [comment]
import '../../static/js/china.js' 
import china from '@/js_sdk/yanhao-echarts-for-wx/uni-ec-canvas/china.json'
import echart from '@/js_sdk/yanhao-echarts-for-wx/uni-ec-canvas/echarts.js'
import uniEcCanvas from '@/js_sdk/yanhao-echarts-for-wx/uni-ec-canvas/uni-ec-canvas';

echart.registerMap('china', china)

**Comment by ghostsGod** [comment]
其他的是摘抄的他发的那段代码，就是这里有以下改动，china那两个是我从码云中名字是uni-app-echarts-map拿到的，好像是您写的吧

**Comment by ghostsGod** [comment]
找到问题了，已经解决，非常感谢

**Comment by ghostsGod** [comment]
按照那个方法写确实可以实现引入

**Comment by Zhuyi731** [comment]
应该是module.exports 要改成export default

**Comment by ghostsGod** [comment]
可以再问您一个问题么？我怎么在单页面多个图表的情况下，给单个的图表添加点击事件，或者是获取到我点击或者滑过的地点名称呢？

**Comment by Zhuyi731** [comment]
> 可以再问您一个问题么？我怎么在单页面多个图表的情况下，给单个的图表添加点击事件，或者是获取到我点击或者滑过的地点名称呢？

通过给你需要的图表添加ref，然后通过this.$refs.$curChart来获取到图表的实例。然后就可以添加事件了

**Comment by ghostsGod** [comment]
> > 可以再问您一个问题么？我怎么在单页面多个图表的情况下，给单个的图表添加点击事件，或者是获取到我点击或者滑过的地点名称呢？
> 
> 通过给你需要的图表添加ref，然后通过this。$ refs。$ curChart来获取到图表的实例。然后就可以添加事件了

<uni-ec-canvas class="uni-ec-canvas" id="line-chart" canvas-id="multi-charts-line" :ec="ec5" ref="canvas"></uni-ec-canvas>
然后this.$refs['canvas'].$curChart是这样吗？
获取实例添加事件我没有太懂，在哪里添加呢

**Comment by ghostsGod** [comment]
<uni-ec-canvas class="uni-ec-canvas" id="line-chart" canvas-id="multi-charts-line" :ec="ec5" ref="canvas"></uni-ec-canvas>
然后this.$refs['canvas'].$curChart是这样吗？
但是怎么获取实例添加事件我没有太懂

**Comment by Zhuyi731** [comment]
> 然后this.$refs['canvas'].$curChart是这样吗？
> 但是怎么获取实例添加事件我没有太懂

是的    添加时间看这个[官方文档 ](https://echarts.apache.org/zh/api.html#events.%E9%BC%A0%E6%A0%87%E4%BA%8B%E4%BB%B6)   click事件改为tap

**Comment by ghostsGod** [comment]
非常抱起还得打扰一下，我还是对着个事件在哪里添加有疑惑，
怎么去设置事件，并且让实例去监听调用呢，您可以告诉我一个大概思路么？

**Comment by Zhuyi731** [comment]
`
const chart = this.$refs['canvas'].$curChart   

chart.on('legendselectchanged', function (params) { //标题被点击事件
    console.log(params);
});
`
