### ISSUE TITLE
无法描述之错误

### ISSUE THREAD

**Issue by WangXinYu-China** [Zhuyi731/echarts-for-wx-uniapp#17]
VM9227:1 TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Wl'
    |     property '_dom' -> object with constructor 'WxCanvas'
    --- property 'chart' closes the circle

表现描述： 进到页面开始报错，之后所有共21个页面所有的前端交互全部崩盘。

求助，可有大神解答

**Comment by Zhuyi731** [comment]
在

> VM9227:1 TypeError: Converting circular structure to JSON
> --> starting at object with constructor 'Wl'
> | property '_dom' -> object with constructor 'WxCanvas'
> --- property 'chart' closes the circle
> 
> 表现描述： 进到页面开始报错，之后所有共21个页面所有的前端交互全部崩盘。
> 
> 求助，可有大神解答

这个是因为data里有一个循环引用的对象，你可以将这个对象名称设置为$开头的就解决了

**Comment by theForagingPawns** [comment]
> 在
> 
> > VM9227:1 TypeError: Converting circular structure to JSON
> > --> starting at object with constructor 'Wl'
> > | property '_dom' -> object with constructor 'WxCanvas'
> > --- property 'chart' closes the circle
> > 表现描述： 进到页面开始报错，之后所有共21个页面所有的前端交互全部崩盘。
> > 求助，可有大神解答
> 
> 这个是因为data里有一个循环引用的对象，你可以将这个对象名称设置为$开头的就解决了

在的，清楚是什么原因导致的么

**Comment by WangXinYu-China** [comment]
> 在
> 
> > VM9227:1 TypeError: Converting circular structure to JSON
> > --> starting at object with constructor 'Wl'
> > | property '_dom' -> object with constructor 'WxCanvas'
> > --- property 'chart' closes the circle
> > 表现描述： 进到页面开始报错，之后所有共21个页面所有的前端交互全部崩盘。
> > 求助，可有大神解答
> 
> 这个是因为data里有一个循环引用的对象，你可以将这个对象名称设置为$开头的就解决了

好的，谢谢您，我尝试改下

**Comment by Zhuyi731** [comment]
> > 在
> > > VM9227:1 TypeError: Converting circular structure to JSON
> > > --> starting at object with constructor 'Wl'
> > > | property '_dom' -> object with constructor 'WxCanvas'
> > > --- property 'chart' closes the circle
> > > 表现描述： 进到页面开始报错，之后所有共21个页面所有的前端交互全部崩盘。
> > > 求助，可有大神解答
> > 
> > 
> > 这个是因为data里有一个循环引用的对象，你可以将这个对象名称设置为$开头的就解决了
> 
> 在的，清楚是什么原因导致的么

uni-app在转编译时会对data对象做JSON.stringify。 如果data有循环引用就会导致栈溢出。而以$开头的对象不会被处理，这也是为什么这里面实例获取要以$curChart来获取的原因

**Comment by WangXinYu-China** [comment]
`data() {
		return {
			active: 0,
			todyStudyTime: null,
			weekStudyTime: null,
			accuracy: null,
			practicedNum: 0,
			show: false,
			columns: [],
			graspedKnowledge: 0,
			allKnowledge: 0,
			nowKnowledge: '',
			ec: {
				lazyLoad:true,
				option: {
				  color: ['#3398DB'],
					  tooltip: {
						  trigger: 'axis',
						  axisPointer: {            // 坐标轴指示器，坐标轴触发有效
							  type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
						  }
					  },
					  grid: {
						  left: '3%',
						  right: '4%',
						  bottom: '3%',
						  containLabel: true
					  },
					  xAxis: [
						  {
							  type: 'category',
							  data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
							  axisTick: {
								  alignWithLabel: true
							  }
						  }
					  ],
					  yAxis: [
						  {
							  type: 'value'
						  }
					  ],
					  series: [
						  {
							  name: '直接访问',
							  type: 'bar',
							  barWidth: '60%',
							  data: [10, 52, 200, 334, 390, 330, 220]
						  }
					  ]
				}
			},
			eca: {
				lazyLoad:true,
				option: {
				  color: ['#3398DB'],
					  tooltip: {
						  trigger: 'axis',
						  axisPointer: {            // 坐标轴指示器，坐标轴触发有效
							  type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
						  }
					  },
					  grid: {
						  left: '3%',
						  right: '4%',
						  bottom: '3%',
						  containLabel: true
					  },
					  xAxis: [
						  {
							  type: 'category',
							  data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
							  axisTick: {
								  alignWithLabel: true
							  }
						  }
					  ],
					  yAxis: [
						  {
							  type: 'value'
						  }
					  ],
					  series: [
						  {
							  name: '直接访问',
							  type: 'bar',
							  barWidth: '60%',
							  data: [10, 52, 200, 334, 390, 330, 220]
						  }
					  ]
				}
			}
		}
	}`


我所有的 data数据都在这里了，您有时间的时候方便看下么   没找到症结所在

> > > `data() { return { active: 0, todyStudyTime: null, weekStudyTime: null, accuracy: null, practicedNum: 0, show: false, columns: [], graspedKnowledge: 0, allKnowledge: 0, nowKnowledge: '', ec: { lazyLoad:true, option: { color: ['#3398DB'], tooltip: { trigger: 'axis', axisPointer: { // 坐标轴指示器，坐标轴触发有效 type: 'shadow' // 默认为直线，可选为：'line' | 'shadow' } }, grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true }, xAxis: [ { type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], axisTick: { alignWithLabel: true } } ], yAxis: [ { type: 'value' } ], series: [ { name: '直接访问', type: 'bar', barWidth: '60%', data: [10, 52, 200, 334, 390, 330, 220] } ] } }, eca: { lazyLoad:true, option: { color: ['#3398DB'], tooltip: { trigger: 'axis', axisPointer: { // 坐标轴指示器，坐标轴触发有效 type: 'shadow' // 默认为直线，可选为：'line' | 'shadow' } }, grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true }, xAxis: [ { type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], axisTick: { alignWithLabel: true } } ], yAxis: [ { type: 'value' } ], series: [ { name: '直接访问', type: 'bar', barWidth: '60%', data: [10, 52, 200, 334, 390, 330, 220] } ] } } } }`
> > > 我所有的 data数据都在这里了，您有时间的时候方便看下么 没找到症结所在
> > 
> > 
> > 我等会看下，找到问题了回复你。 看起来是组件内部的chart循环了
> 
> 页面需要两个chart，我先放两个在这里，改了下id、ref、canvas-id，就先扔那了。将其中一个注释掉，依然存在上述问题。

**Comment by Zhuyi731** [comment]
> `data() { return { active: 0, todyStudyTime: null, weekStudyTime: null, accuracy: null, practicedNum: 0, show: false, columns: [], graspedKnowledge: 0, allKnowledge: 0, nowKnowledge: '', ec: { lazyLoad:true, option: { color: ['#3398DB'], tooltip: { trigger: 'axis', axisPointer: { // 坐标轴指示器，坐标轴触发有效 type: 'shadow' // 默认为直线，可选为：'line' | 'shadow' } }, grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true }, xAxis: [ { type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], axisTick: { alignWithLabel: true } } ], yAxis: [ { type: 'value' } ], series: [ { name: '直接访问', type: 'bar', barWidth: '60%', data: [10, 52, 200, 334, 390, 330, 220] } ] } }, eca: { lazyLoad:true, option: { color: ['#3398DB'], tooltip: { trigger: 'axis', axisPointer: { // 坐标轴指示器，坐标轴触发有效 type: 'shadow' // 默认为直线，可选为：'line' | 'shadow' } }, grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true }, xAxis: [ { type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], axisTick: { alignWithLabel: true } } ], yAxis: [ { type: 'value' } ], series: [ { name: '直接访问', type: 'bar', barWidth: '60%', data: [10, 52, 200, 334, 390, 330, 220] } ] } } } }`
> 
> 我所有的 data数据都在这里了，您有时间的时候方便看下么 没找到症结所在

 我等会看下，找到问题了回复你。  看起来是组件内部的chart循环了

**Comment by WangXinYu-China** [comment]
> > `data() { return { active: 0, todyStudyTime: null, weekStudyTime: null, accuracy: null, practicedNum: 0, show: false, columns: [], graspedKnowledge: 0, allKnowledge: 0, nowKnowledge: '', ec: { lazyLoad:true, option: { color: ['#3398DB'], tooltip: { trigger: 'axis', axisPointer: { // 坐标轴指示器，坐标轴触发有效 type: 'shadow' // 默认为直线，可选为：'line' | 'shadow' } }, grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true }, xAxis: [ { type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], axisTick: { alignWithLabel: true } } ], yAxis: [ { type: 'value' } ], series: [ { name: '直接访问', type: 'bar', barWidth: '60%', data: [10, 52, 200, 334, 390, 330, 220] } ] } }, eca: { lazyLoad:true, option: { color: ['#3398DB'], tooltip: { trigger: 'axis', axisPointer: { // 坐标轴指示器，坐标轴触发有效 type: 'shadow' // 默认为直线，可选为：'line' | 'shadow' } }, grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true }, xAxis: [ { type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], axisTick: { alignWithLabel: true } } ], yAxis: [ { type: 'value' } ], series: [ { name: '直接访问', type: 'bar', barWidth: '60%', data: [10, 52, 200, 334, 390, 330, 220] } ] } } } }`
> > 我所有的 data数据都在这里了，您有时间的时候方便看下么 没找到症结所在
> 
> 我等会看下，找到问题了回复你。 看起来是组件内部的chart循环了

页面需要两个chart，我先放两个在这里，改了下id、ref、canvas-id，就先扔那了。将其中一个注释掉，依然存在上述问题。

**Comment by Zhuyi731** [comment]
> > > `data() { return { active: 0, todyStudyTime: null, weekStudyTime: null, accuracy: null, practicedNum: 0, show: false, columns: [], graspedKnowledge: 0, allKnowledge: 0, nowKnowledge: '', ec: { lazyLoad:true, option: { color: ['#3398DB'], tooltip: { trigger: 'axis', axisPointer: { // 坐标轴指示器，坐标轴触发有效 type: 'shadow' // 默认为直线，可选为：'line' | 'shadow' } }, grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true }, xAxis: [ { type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], axisTick: { alignWithLabel: true } } ], yAxis: [ { type: 'value' } ], series: [ { name: '直接访问', type: 'bar', barWidth: '60%', data: [10, 52, 200, 334, 390, 330, 220] } ] } }, eca: { lazyLoad:true, option: { color: ['#3398DB'], tooltip: { trigger: 'axis', axisPointer: { // 坐标轴指示器，坐标轴触发有效 type: 'shadow' // 默认为直线，可选为：'line' | 'shadow' } }, grid: { left: '3%', right: '4%', bottom: '3%', containLabel: true }, xAxis: [ { type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], axisTick: { alignWithLabel: true } } ], yAxis: [ { type: 'value' } ], series: [ { name: '直接访问', type: 'bar', barWidth: '60%', data: [10, 52, 200, 334, 390, 330, 220] } ] } } } }`
> > > 我所有的 data数据都在这里了，您有时间的时候方便看下么 没找到症结所在
> > 
> > 
> > 我等会看下，找到问题了回复你。 看起来是组件内部的chart循环了
> 
> 页面需要两个chart，我先放两个在这里，改了下id、ref、canvas-id，就先扔那了。将其中一个注释掉，依然存在上述问题。

![image](https://user-images.githubusercontent.com/17618307/88888871-b2230b80-d271-11ea-9fe2-6baf1046b7a4.png)
能把你完整代码贴一下吗  我这里似乎没出现这个问题

**Comment by WangXinYu-China** [comment]
`<template>
	<view class="study_report_page">
		<div class='top_title' @click='showPopup'>
			学习报告
		</div>
		<van-tabs :active="active" @change="onChange">
			<van-tab title="近期数据">
				<div class='tody_data'>
					<div>今日学习</div>
					<div>
						<span style='font-weight: bold;'>{{todyStudyTime}}</span>
						<span>分钟</span>
					</div>
				</div>
				<div class='tody_data'>
					<div>本周学习</div>
					<div>
						<span style='font-weight: bold;'>{{weekStudyTime}}</span>
						<span>分钟</span>
					</div>
				</div>
				<div class='chart_data'>
					<div class='top_describe'>
						<div>近七天学习</div>
						<div>单位：分钟</div>
					</div>
					<div class="echarts_block">
						<uni-ec-canvas
							class="uni-ec-canvas"
							id="line-chart"
							ref="canvas"
							canvas-id="lazy-load-chart"
							:ec="ec"
						></uni-ec-canvas>
					</div>
				</div>
				<div class='chart_data'>
					<div class='top_describe'>
						<div>近七天学习</div>
						<div>单位：分钟</div>
					</div>
					<div class="echarts_block">
						<uni-ec-canvas
							class="uni-ec-canvas"
							id="line-charta"
							ref="canvasa"
							canvas-id="lazy-load-charta"
							:ec="eca"
						></uni-ec-canvas>
					</div>
				</div>
				<div class='chart_data'>
					<div class='top_describe'>
						<div>近七天高频知识点错题</div>
						<div></div>
					</div>
					<div class='detail_describe'>
						<text class="iconfont icontubiao1" style='font-size: 60rpx;color: #F99C2B;flex:1;text-align: center;'></text>
						<div style='flex:1'>123</div>
						<button type="primary" style='flex:1;margin-right: 50rpx;'>现在学习</button>
					</div>
				</div>
			</van-tab>
			<van-tab title="累计战绩">
				<div class='data_general_view'>
					<div style='font-size: 38rpx;' is-link @click='showPopup'>{{nowKnowledge}}<text class="iconfont iconzhankai-copy-copy"></text></div>
					<div class='generalView_ball'>
						<span style='font-size: 60rpx;'>{{graspedKnowledge}}</span>
						<span>/{{allKnowledge}}</span>
					</div>
					<div style='color: #656A6D;'>已掌握知识点</div>
				</div>
				<div class='practice_situation'>
					<div style='font-size: 38rpx;margin-bottom: 10rpx;'>题目练习情况</div>
					<div style='color: #656A6D;margin-bottom: 30rpx;'>共完成<span style='color: #F9702B;'>{{practicedNum}}</span>道练习，正确率<span style='color: #F9702B;'>{{accuracy}}</span></div>
					<div class='start_btn'>
						
						<div @click='toWrongExercises'>开始错题练习</div>
					</div>
				</div>
				<div class="bottom_block">
					<div class='bottom_title'>
						<text class="iconfont icontubiao1" style='font-size: 32rpx;color: #F99C2B;'></text>
						<span style='font-size: 32rpx;margin-left: 10rpx;'>排行榜</span>
					</div>
					
					<div class='rank_blank' v-for='(item,index) in 4' :key='index'>
						<div class='ranker_info'>
							<span style='font-size: 32rpx;color: #E94E4E;font-weight: bolder;'>1</span>
							<div class='ranker_avatar'>头像</div>
							<span style='font-size: 32rpx;color: #E94E4E;'>[名字]</span>
						</div>
						<div class='ranker_ranking'>
							答对<span style='color: #E94E4E;'>XX</span>题
						</div>
					</div>
				</div>
				
				<van-popup
					:show="show" 
					position="bottom" 
					@close="onClose" 
					closeable
					close-on-click-overlay
				>
					<van-picker
					    :columns="columns"
					    default-index="0"
					    @change="onPickerChange"
						value-key='name'
					/>
				</van-popup>
			</van-tab>
		</van-tabs>
		
	</view>
</template>

<script>
import { turnToMinute } from '../../utils/index.js'
import uniEcCanvas from '../../uni-ec-canvas/uni-ec-canvas.vue'
import * as echarts from '../../uni-ec-canvas/echarts'
export default {
	data() {
		return {
			active: 0,
			todyStudyTime: null,
			weekStudyTime: null,
			accuracy: null,
			practicedNum: 0,
			show: false,
			columns: [],
			graspedKnowledge: 0,
			allKnowledge: 0,
			nowKnowledge: '',
			ec: {
				lazyLoad:true,
				option: {
				  color: ['#3398DB'],
					  tooltip: {
						  trigger: 'axis',
						  axisPointer: {            // 坐标轴指示器，坐标轴触发有效
							  type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
						  }
					  },
					  grid: {
						  left: '3%',
						  right: '4%',
						  bottom: '3%',
						  containLabel: true
					  },
					  xAxis: [
						  {
							  type: 'category',
							  data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
							  axisTick: {
								  alignWithLabel: true
							  }
						  }
					  ],
					  yAxis: [
						  {
							  type: 'value'
						  }
					  ],
					  series: [
						  {
							  name: '直接访问',
							  type: 'bar',
							  barWidth: '60%',
							  data: [10, 52, 200, 334, 390, 330, 220]
						  }
					  ]
				}
			},
			eca: {
				lazyLoad:true,
				option: {
				  color: ['#3398DB'],
					  tooltip: {
						  trigger: 'axis',
						  axisPointer: {            // 坐标轴指示器，坐标轴触发有效
							  type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
						  }
					  },
					  grid: {
						  left: '3%',
						  right: '4%',
						  bottom: '3%',
						  containLabel: true
					  },
					  xAxis: [
						  {
							  type: 'category',
							  data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
							  axisTick: {
								  alignWithLabel: true
							  }
						  }
					  ],
					  yAxis: [
						  {
							  type: 'value'
						  }
					  ],
					  series: [
						  {
							  name: '直接访问',
							  type: 'bar',
							  barWidth: '60%',
							  data: [10, 52, 200, 334, 390, 330, 220]
						  }
					  ]
				}
			}
		}
	},
	onReady () {
	    setTimeout(()=>{
	        this.$refs['canvas'].init()
			this.$refs['canvasa'].init()
	    },1000) // 两秒之后延迟加载
	
	    setTimeout(()=>{
			this.ec.option.series[0].data = [120, 132, 101, 134, 90, 230, 210]
			this.ec.option.xAxis[0].data = [1,2,3,4,5,6,7]
			this.eca.option.series[0].data = [120, 132, 101, 134, 90, 230, 210]
			this.eca.option.xAxis[0].data = [1,2,3,4,5,6,7]
	    },2000)
	  },
	components: {
	    uniEcCanvas
	},
	mounted() {
		this.getStudyInfo();
		this.getPracticeHistory();
	},
	methods: {
		onChange(event) {
			console.log('切换到标签',event.detail.name)
		},
		getStudyInfo() {
			this.$api.getStudyInfo().then(({data}) => {
				console.log('获取近七天学习数据',data)
				this.todyStudyTime = turnToMinute(data.studyToday);
				this.weekStudyTime = turnToMinute(data.studyWeek);
			})
		},
		getPracticeHistory() {
			this.$api.getPracticeHistory().then(({data}) => {
				console.log('获取近七天练习数据',data)
				this.columns = data
				this.graspedKnowledge = this.columns[1].count
				this.allKnowledge = this.columns[1].total
				this.nowKnowledge = this.columns[1].name
				this.practicedNum = this.columns[1].total
				this.accuracy = this.columns[1].accuracy
			})
		},
		showPopup() {
		    this.show = true;
		},
		
		onClose() {
			this.show = false;
		},
		onPickerChange(e) {
			this.graspedKnowledge = e.detail.value.count
			this.allKnowledge = e.detail.value.total
			this.nowKnowledge = e.detail.value.name
		},
		toWrongExercises() {
			uni.navigateTo({
				url: `/pages/wrongExercises/wrongExercises?knowledge=${this.nowKnowledge}`
			})
		}
	}
}
</script>

<style lang="scss">
.study_report_page {
	width: 100%;
	overflow: auto;
	background: white;
	.top_title {
		height: 180rpx;
		background: white;
		position: relative;
		line-height: 80rpx;
		text-align: center;
		font-weight: bold;
		font-size: 48rpx;
	}
	.van-tab {
		background: #F5F6F7;
	}
	.tody_data {
		display: flex;
		justify-content: space-between;
		padding: 5%;
		border-bottom: 30rpx solid #F5F6F7;
		height: 180rpx !important;
		line-height: 180rpx;
		align-items: center;
		font-size: 38rpx;
	}
	.chart_data {
		.top_describe {
			display: flex;
			justify-content: space-between;
			padding: 3% 5%;
		}
		.echarts_block {
			width: 100%;
			height: 400rpx;
			border-bottom: 30rpx solid #F5F6F7;
		}
		.detail_describe {
			display: flex;
			justify-content: space-between;
			align-items: center;
			margin-bottom: 60rpx;
		}
	}
	.data_general_view {
		display: flex;
		flex-direction: column;
		align-items: center;
		border-bottom: 30rpx solid #F5F6F7;
		padding: 3%;
		div {
			display: inline-block;
		}
		.generalView_ball {
			width: 200rpx;
			height: 200rpx;
			line-height: 200rpx;
			text-align: center;
			border-radius: 50%;
			box-shadow: #CECECE 0px 0px 15rpx;
			margin: 20rpx 10%;
		}
	}
	.practice_situation {
		padding: 5%;
		border-bottom: 30rpx solid #F5F6F7;
		.start_btn {
			text-align: right;
			div {
				display: inline-block;
				width: 55%;
				height: 70rpx;
				line-height: 70rpx;
				background: #F9702B;
				text-align: center;
				border-radius: 10rpx;
				color: white;
			}
		}
	}
	.bottom_block {
		margin: 20rpx 40rpx;
		border-radius: 2rpx;
		padding: 3% 2%;
		.rank_blank {
			display: flex;
			justify-content: space-between;
			margin: 10rpx 0;
			height: 80rpx;
			line-height: 80rpx;
			.ranker_info {
				display: flex;
				justify-content: space-between;
				.ranker_avatar {
					display: inline-block;
					width: 80rpx;
					height: 80rpx;
					border-radius: 50%;
					border: 1px solid #C8C8C8;
					text-align: center;
					margin: 0 10rpx;
				}
			}
		}
	}
	.uni-ec-canvas{
	    width: 750upx;
	    height: 750upx;
	    display:block;
	}
}
</style>
`

嗯  界面  可以出来   我这也是两个echarts都出来了   全部的

**Comment by WangXinYu-China** [comment]
![效果图.png](https://upload-images.jianshu.io/upload_images/19882252-4646152915f26f74.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by Zhuyi731** [comment]
我试了各种姿势，在我这里没法复现，你可能需要进入错误里面看一下是哪个对象循环了。
还有  
`import * as echarts from '../../uni-ec-canvas/echarts' `  
这段是不需要的

**Comment by WangXinYu-China** [comment]
好的   谢谢了

**Comment by WangXinYu-China** [comment]
兄弟  我发现我这里是页面离开的时候  报的这个错误   这就很难受
