### ISSUE TITLE
将example里的例子  完整移植到项目中  报错如下

### ISSUE THREAD

**Issue by WangXinYu-China** [Zhuyi731/echarts-for-wx-uniapp#18]

**Comment by WangXinYu-China** [comment]
![错误截图.png](https://upload-images.jianshu.io/upload_images/19882252-905d7ff309def9c1.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by Zhuyi731** [comment]
咋出现的？  我这完全没法复现啊😂
