### ISSUE TITLE
页面未显示

### ISSUE THREAD

**Issue by nooneqwq** [Zhuyi731/echarts-for-wx-uniapp#19]
<template>
	<view>
	       <uni-ec-canvas 
	          class="uni-ec-canvas"
	          id="uni-ec-canvas"
	          ref="uni-ec-canvas"
	          canvas-id="uni-ec-canvas"
	          :ec="ec"
	       ></uni-ec-canvas>
	    </view>
</template>

<script>
	/*export default {
	  onLoad() {
	    
	  },
	  data() {
	    return {
	      
		  }
	  },
	  methods: {
	    
	
	  },
	};*/
	import uniEcCanvas from '../../components/uni-ec-canvas/uni-ec-canvas.vue'  
	
	export default{
	    data(){ 
	        return {
	            ec:{
	                option:{
						title: {
					            text: 'ECharts 入门示例'
					            },
					            tooltip: {},
					            legend: {
					                data:['销量']
					            },
					            xAxis: {
					                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
					            },
					            yAxis: {},
					            series: [{
					                name: '销量',
					                type: 'bar',
					                data: [5, 20, 36, 10, 10, 20]
					            }]
					} //echart 配置项
	            }
	        }
	    },
	    components:{
	        uniEcCanvas
	    }
	};
</script>

<style>
	.uni-ec-canvas{
	    width:100%;
	    height:100%;
	    display:block;
		}
</style>
代码如上，页面空白未显示图表。

**Comment by Zhuyi731** [comment]
> <script> /*export default { onLoad() { }, data() { return { } }, methods: { }, };*/ import uniEcCanvas from '../../components/uni-ec-canvas/uni-ec-canvas.vue' export default{ data(){ return { ec:{ option:{ title: { text: 'ECharts 入门示例' }, tooltip: {}, legend: { data:['销量'] }, xAxis: { data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"] }, yAxis: {}, series: [{ name: '销量', type: 'bar', data: [5, 20, 36, 10, 10, 20] }] } //echart 配置项 } } }, components:{ uniEcCanvas } }; </script> <style> .uni-ec-canvas{ width:100%; height:100%; display:block; } </style>
> 代码如上，页面空白未显示图表。

你这里没有定义组件的宽高，必须要定义指定的宽高才能显示，readme中有写

**Comment by nooneqwq** [comment]
> > <script> /*export default { onLoad() { }, data() { return { } }, methods: { }, };*/ import uniEcCanvas from '../../components/uni-ec-canvas/uni-ec-canvas.vue' export default{ data(){ return { ec:{ option:{ title: { text: 'ECharts 入门示例' }, tooltip: {}, legend: { data:['销量'] }, xAxis: { data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"] }, yAxis: {}, series: [{ name: '销量', type: 'bar', data: [5, 20, 36, 10, 10, 20] }] } //echart 配置项 } } }, components:{ uniEcCanvas } }; </script> <style> .uni-ec-canvas{ width:100%; height:100%; display:block; } </style>
> > 代码如上，页面空白未显示图表。
> 
> 你这里没有定义组件的宽高，必须要定义指定的宽高才能显示，readme中有写

谢谢
