### ISSUE TITLE
uniapp里使用报错

### ISSUE THREAD

**Issue by yah0130** [Zhuyi731/echarts-for-wx-uniapp#2]
错误信息
Cannot use 'in' operator to search for '_ec_inner' in undefined;at SelectorQuery callback function
TypeError: Cannot use 'in' operator to search for '_ec_inner' in undefined

**Comment by Zhuyi731** [comment]
能提供一下复现的代码吗？

**Comment by yah0130** [comment]
刚解决了是外面漏了一层option帮我关闭吧😂

发自我的iPhone

在 2020年1月8日，11:29，Incarnation <notifications@github.com> 写道：

﻿

能提供一下复现的代码吗？
