### ISSUE TITLE
uniapp使用报错，真机调试也报错，无法显示

### ISSUE THREAD

**Issue by guoguo-lu** [Zhuyi731/echarts-for-wx-uniapp#20]
开发工具报错：
MiniProgramError
Cannot use 'in' operator to search for '_ec_inner' in undefined
TypeError: Cannot use 'in' operator to search for '_ec_inner' in undefined
真机调试报错：
eval script evaluate_id #108 failed ReferenceError: HTMLCanvasView is not defined

**Comment by Zhuyi731** [comment]
代码能给一下吗  怎么用的
