### ISSUE TITLE
获取不到图表

### ISSUE THREAD

**Issue by niconicoli** [Zhuyi731/echarts-for-wx-uniapp#21]
this.$refs['uni-ec-canvas'].$curChart 获取不到chart实例 显示未unified

**Comment by Zhuyi731** [comment]
有几个要注意的地方
1. 如果是一进页面就去获取，此时还未渲染，$curChart实例为空   
2. 如果是延迟加载，则需要在init之后才获取  

可以通过监听inited事件来获取chart实例

**Comment by Zhuyi731** [comment]
我更新了下README
