### ISSUE TITLE
华为手机进入小程序无法显示图表X轴和Y轴，提示框也报错 ios可以正常显示

### ISSUE THREAD

**Issue by niconicoli** [Zhuyi731/echarts-for-wx-uniapp#22]

**Comment by Zhuyi731** [comment]
> _No description provided._

具体手机的兼容问题无法帮忙修复，一般是小程序canvas的兼容问题。  可以寻找相关的hack方案来解决

**Comment by niconicoli** [comment]
能给一个具体点的吗 找了好久没找到解决方案

**Comment by Zhuyi731** [comment]
> 能给一个具体点的吗 找了好久没找到解决方案

能给一下具体的表现截图和代码吗

**Comment by Zhuyi731** [comment]
可以先试一下  grid 调整x y轴位置  
`grid: {
         x: 70,
         y: 10
       }
`

**Comment by niconicoli** [comment]
改了  不行

**Comment by niconicoli** [comment]
找到问题了 是华为手机不显示数字 显示文字是可以的

**Comment by niconicoli** [comment]
不是被遮挡了 是无法显示 X轴用汉字可以显示 用数字不行  Y轴用数字和汉字都不能显示

**Comment by niconicoli** [comment]
[https://github.com/ecomfe/echarts-for-weixin/issues/619](url) 和这个是一样的问题  具体截图可以看这上面的

**Comment by Zhuyi731** [comment]
微信小程序基础库2.11.0已修复
