### ISSUE TITLE
不支持formatter么？

### ISSUE THREAD

**Issue by tryhank** [Zhuyi731/echarts-for-wx-uniapp#23]
我在echarts-for-weixin上测试是支持的呀

**Comment by Zhuyi731** [comment]
> 我在echarts-for-weixin上测试是支持的呀

支持的，这个是因为uni-app在处理data对象时会使用json.stringify和json.parse导致函数丢失。
需要通过获取实例$curChart后。通过this.$curChart.setOption来设置echart配置

**Comment by tryhank** [comment]
好的，我试试，感谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zhuyi731/echarts-for-wx-uniapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月20日(星期二) 上午9:48
收件人:&nbsp;"Zhuyi731/echarts-for-wx-uniapp"<echarts-for-wx-uniapp@noreply.github.com&gt;;
抄送:&nbsp;"神龙摆尾"<742721238@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zhuyi731/echarts-for-wx-uniapp] 不支持formatter么？ (#23)





  
我在echarts-for-weixin上测试是支持的呀
  
支持的，这个是因为uni-app在处理data对象时会使用json.stringify和json.parse导致函数丢失。
 需要通过获取实例$curChart后。通过this.$curChart.setOption来设置echart配置

**Comment by Zhuyi731** [comment]
这个方法可行吗？

**Comment by tryhank** [comment]
可以，返回的实例setOption就可以了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zhuyi731/echarts-for-wx-uniapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月20日(星期二) 下午4:35
收件人:&nbsp;"Zhuyi731/echarts-for-wx-uniapp"<echarts-for-wx-uniapp@noreply.github.com&gt;;
抄送:&nbsp;"神龙摆尾"<742721238@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zhuyi731/echarts-for-wx-uniapp] 不支持formatter么？ (#23)





 
这个方法可行吗？
