### ISSUE TITLE
echarts图表底层的canvas不会随着页面滚动，与外层点击位置不同步

### ISSUE THREAD

**Issue by Enjoy-yuan** [Zhuyi731/echarts-for-wx-uniapp#24]

**Comment by small-account** [comment]
能具体给出代码或者截屏吗

**Comment by Zhuyi731** [comment]
能给出具体的代码或者截屏吗

**Comment by Enjoy-yuan** [comment]
![image](https://user-images.githubusercontent.com/49602361/99328090-575fff00-28b6-11eb-9b5d-79fdb9b86024.png)

加上force-use-old-canvas="true"可以解决，multi-charts的例子把页面的高度撑到可以滚动就能复现这个了
