### ISSUE TITLE
formatter函数被序列化

### ISSUE THREAD

**Issue by wuufeii** [Zhuyi731/echarts-for-wx-uniapp#26]
![image](https://user-images.githubusercontent.com/30976736/99614831-41d50b80-2a55-11eb-93b5-e8a0c100478a.png)
我看到之前回答用$curChart.setOption方法；是我截图那样写的吗？怎么报错

**Comment by Zhuyi731** [comment]
不能再onLoad的时候使用。onLoad时，图表还没初始化完毕，会获取不到$curChart  
可以通过监听uni-ec-canvas的inited事件，等事件触发再去setOption
[文档中有说明](https://github.com/Zhuyi731/echarts-for-wx-uniapp#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E5%9B%BE%E8%A1%A8%E5%AE%9E%E4%BE%8B)

**Comment by wuufeii** [comment]
那怎么判断组件是否初始化完成呢？还有你说的inited事件我没有看到呀，怎么去监听它

**Comment by Zhuyi731** [comment]
```html
<uni-ec-canvas @inited="inited" />
```

```js
export default {
    methods: {
           inited(curChart){
                  console.log('这时候图表初始化完成了') 
           }
    }
}

**Comment by Zhuyi731** [comment]
你需要看下uni-ec-canvas.vue这个文件里有没有这行，没有的话需要更新下代码。
![image](https://user-images.githubusercontent.com/17618307/99617290-0557de80-2a5a-11eb-9e51-714a47001d6c.png)

**Comment by wuufeii** [comment]
我看到了，我从uniapp插件库那边导入的项目；那边没有this.$emit('inited')；我从你github拉取最新的吧，谢谢了

**Comment by wuufeii** [comment]
嗯嗯，我看到了，之前是没有，我现在加上
