### ISSUE TITLE
无法使用函数打印数据，return无效

### ISSUE THREAD

**Issue by Enjoy-yuan** [Zhuyi731/echarts-for-wx-uniapp#27]
// 使用itemStyle设置bar的颜色，return无效，console无法打印

<template>
  <view>
    <uni-ec-canvas class="uni-ec-canvas" :ec="ec"></uni-ec-canvas>
  </view>
</template>

<script>
import uniEcCanvas from '@/components/uni-ec-canvas/uni-ec-canvas'
export default {
  components: {
    uniEcCanvas
  },
  data() {
    return {
      ec: {
        option: {
          xAxis: {
            type: 'category',
            data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
          },
          yAxis: {
            type: 'value'
          },
          series: [
            {
              data: [120, 200, 150, 80, 70, 110, 130],
              type: 'bar',
              showBackground: true,
              backgroundStyle: {
                color: 'rgba(220, 220, 220, 0.8)'
              },
              itemStyle: {
                color: (info) => {
                  console.log(info)
                  return 'green'
                }
              }
            }
          ]
        }
      }
    }
  }
}
</script>

<style scoped>
.uni-ec-canvas {
  width: 750upx;
  height: 750upx;
  display: block;
}
</style>

**Comment by Zhuyi731** [comment]
函数需要使用setOption  见这个 [issue](https://github.com/Zhuyi731/echarts-for-wx-uniapp/issues/3)
