### ISSUE TITLE
formatter用function方式不起作用

### ISSUE THREAD

**Issue by yah0130** [Zhuyi731/echarts-for-wx-uniapp#3]
formatter用function方式不起作用

**Comment by Zhuyi731** [comment]
> formatter用function方式不起作用

因为option在data里面uni-app会有个序列化然后反序列化，会把所有函数去掉，所以需要手动设置option。
`this.$refs.ecChart.$curChart.setOption(yourOption)`

**Comment by yah0130** [comment]
嗯好了

发自我的iPhone

在 2020年1月9日，18:18，Incarnation <notifications@github.com> 写道：

﻿

formatter用function方式不起作用

因为option在data里面uni-app会有个序列化然后反序列化，会把所有函数去掉，所以需要手动设置option。
this.$refs.ecChart.$curChart.setOption(yourOption)
