### ISSUE TITLE
组件脱离文档流

### ISSUE THREAD

**Issue by Runcode-China** [Zhuyi731/echarts-for-wx-uniapp#31]

**Comment by Runcode-China** [comment]
![image](https://user-images.githubusercontent.com/66289053/116819212-a0c0b400-aba1-11eb-8ccb-2e2615cff1cd.png)
![image](https://user-images.githubusercontent.com/66289053/116819219-ac13df80-aba1-11eb-887d-3c6b4b196e44.png)
![image](https://user-images.githubusercontent.com/66289053/116819230-b7ffa180-aba1-11eb-8e4f-d7f84ec59871.png)

**Comment by Zhuyi731** [comment]
cavas是原生组件，如果文档是普通view可能会出现该情况。

**Comment by Runcode-China** [comment]
那请问如何解决这个问题

**Comment by Zhuyi731** [comment]
重新设置样式，或者将页面view替换成cover-view

**Comment by dingxian-dx** [comment]
![image](https://user-images.githubusercontent.com/81401001/118089659-2f7fcd00-b3fb-11eb-81d8-fb57f732f9f2.png)
![image](https://user-images.githubusercontent.com/81401001/118089701-3ad2f880-b3fb-11eb-88c7-6e3e2346c02c.png)
cover-view解决不了该问题，求填坑。

**Comment by dingxian-dx** [comment]
加上 force-use-old-canvas="true"就解决了。作者挖坑呀

**Comment by Runcode-China** [comment]
测试加了force-use-old-canvas="true" 后地图还是会脱离，其他不会

**Comment by dingxian-dx** [comment]
可能地图才有这样的类型吧，不太清楚了就

**Comment by Runcode-China** [comment]
不过你还是挺强的呀，我找了半个月还没解决  你怎么知道解决办法的

**Comment by dingxian-dx** [comment]
![image](https://user-images.githubusercontent.com/81401001/118098571-a40c3900-b406-11eb-8053-16bc6faab7e4.png)
运气好运气好

**Comment by Runcode-China** [comment]
加个微信吗 遇到疑难杂症可以沟通沟通

**Comment by dingxian-dx** [comment]
15151895537




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zhuyi731/echarts-for-wx-uniapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zhuyi731/echarts-for-wx-uniapp] 组件脱离文档流 (#31)





 
加个微信吗 遇到疑难杂症可以沟通沟通

**Comment by dingxian-dx** [comment]
wx 15151895537

**Comment by dingxian-dx** [comment]
wx 15151895537

**Comment by entenity** [comment]
微信 就这样暴露的吗
