### ISSUE TITLE
图表不显示问题

### ISSUE THREAD

**Issue by 18326183038** [Zhuyi731/echarts-for-wx-uniapp#33]
你好，用了你的插件，但是为什么不显示呢？代码如下：
`<template>
    <view>
       <uni-ec-canvas 
          class="uni-ec-canvas"
          id="uni-ec-canvas"
          ref="uni-ec-canvas"
          canvas-id="uni-ec-canvas"
          :ec="ec"
          @inited="inited"
       ></uni-ec-canvas>
    </view>
</template>

<script>
import uniEcCanvas from '@/uni_modules/uni-ec-canvas/uni-ec-canvas.vue'
	export default {
		 data(){
		        return {
		            ec:{
		                option:{							
								xAxis: {
									type: 'category',
									data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
								  },
								  yAxis: {
									type: 'value'
								  },
								  series: [
									{
									  data: [120, 200, 150, 80, 70, 110, 130],
									  type: 'bar'
									}
								  ]
						} //echart 配置项
		            }
		        }
		    },
		    components:{
		        uniEcCanvas
		    },
		    methods:{
		        inited(chart){
		           console.log('图表初始化完毕')
		           console.log('chart实例', chart)
		        }
		    }
	}
	
	

</script>

<style>
.uni-ec-canvas{
    width:100%;
    height:100%;
    display:block;
}
</style>

`
运行到小程序开发工具后：
![image](https://user-images.githubusercontent.com/28560919/139819952-551c08b4-5bc2-4365-8ece-9e2d200934dd.png)
![image](https://user-images.githubusercontent.com/28560919/139819995-04da7f35-fb91-4c16-aba1-bf32e9234f58.png)

**Comment by Zhuyi731** [comment]
> 你好，用了你的插件，但是为什么不显示呢？代码如下： ` <uni-ec-canvas class="uni-ec-canvas" id="uni-ec-canvas" ref="uni-ec-canvas" canvas-id="uni-ec-canvas" :ec="ec" @inited="inited" >
> 
> <script> import uniEcCanvas from '@/uni_modules/uni-ec-canvas/uni-ec-canvas.vue' export default { data(){ return { ec:{ option:{ xAxis: { type: 'category', data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] }, yAxis: { type: 'value' }, series: [ { data: [120, 200, 150, 80, 70, 110, 130], type: 'bar' } ] } //echart 配置项 } } }, components:{ uniEcCanvas }, methods:{ inited(chart){ console.log('图表初始化完毕') console.log('chart实例', chart) } } } </script> <style> .uni-ec-canvas{ width:100%; height:100%; display:block; } </style>
> ` 运行到小程序开发工具后： ![image](https://user-images.githubusercontent.com/28560919/139819952-551c08b4-5bc2-4365-8ece-9e2d200934dd.png) ![image](https://user-images.githubusercontent.com/28560919/139819995-04da7f35-fb91-4c16-aba1-bf32e9234f58.png)

宽高必须设定指定数值，不能为百分比
