### ISSUE TITLE
formatter可以正常运行，但是不支持自定义html标签吗？

### ISSUE THREAD

**Issue by cnpmge** [Zhuyi731/echarts-for-wx-uniapp#37]
formatter: function (params) {
	var d='<view style="transform:rotate(90deg);">abcderg</view>'
	return d; // 见最底层的函数
}

**Comment by Zhuyi731** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Zhuyi731** [comment]
> formatter: function (params) { var d='abcderg' return d; // 见最底层的函数 }

formatter支持函数，可以看下这个[issue](https://github.com/Zhuyi731/echarts-for-wx-uniapp/issues/3)
