### ISSUE TITLE
Put an image in the formatter and report an error Image is not a constructor

### ISSUE THREAD

**Issue by mp2506908869** [Zhuyi731/echarts-for-wx-uniapp#38]
![image](https://user-images.githubusercontent.com/44697083/163138712-ddf5e99e-7673-468a-bdcf-5ab2d7555d51.png)

**Comment by Zhuyi731** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Zhuyi731** [comment]
Mini-program does not support Image constructor. 
You can try canvas.createImage() api

**Comment by mp2506908869** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月13日(星期三) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zhuyi731/echarts-for-wx-uniapp] Put an image in the formatter and report an error Image is not a constructor (Issue #38)





 
小程序不支持 Image 构造函数。
 你可以试试 canvas.createImage() api
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。消息ID：<Zhuyi731/echarts-for-wx-uniapp/issues/38/1097747758 @ github 。com&gt;
