### ISSUE TITLE
滑动事件怎么监听

### ISSUE THREAD

**Issue by yah0130** [Zhuyi731/echarts-for-wx-uniapp#4]
我监听的touchstart结果没有参数传递进来

**Comment by Zhuyi731** [comment]
> 我监听的touchstart结果没有参数传递进来

你怎么监听的 把代码发出来一下。

**Comment by Zhuyi731** [comment]
> 我监听的touchstart结果没有参数传递进来

如果是通过options绑定的，options因为是放在data里所以不支持函数  需要通过refs.$curChart.setOption(yourOption)来绑定

**Comment by yah0130** [comment]
嗯搞定了

发自我的iPhone

在 2020年1月9日，18:16，Incarnation <notifications@github.com> 写道：

﻿

我监听的touchstart结果没有参数传递进来

如果是通过options绑定的，options因为是放在data里所以不支持函数 需要通过refs.$curChart.setOption(yourOption)来绑定
