### ISSUE TITLE
legend的formatter的方法无效

### ISSUE THREAD

**Issue by 3zxsyx** [Zhuyi731/echarts-for-wx-uniapp#43]
legend的formatter的方法无效

ec: {
	option: {
		legend: {
			orient: "vertical",
			top: "center",
			right: "20%",
			formatter: (name) => {
				return name + "   " + option.series[0].data.find((item) => item.name == name).value;
			},
		},
		series: [
			{
				name: "",
				type: "pie",
				radius: "80%",
				left: "-40%",
				label: {
					position: "outside",
					color: "#19193E",
					normal: {
						show: false,
					},
					emphasis: {
						show: true,
					},
					fontSize: 10,
				},
				labelLine: {
					normal: {
						show: false,
					},
					emphasis: {
						show: true,
					},
				},
				data: [
					{
						value: 321,
						name: "普票",
						itemStyle: {
							normal: { color: "#6699FF" },
							emphasis: { color: "#6699FF" },
						},
					},
					{
						value: 1148,
						name: "专票",
						itemStyle: {
							normal: { color: "#52CCA3" },
							emphasis: { color: "#52CCA3" },
						},
					},
				],
			},
		],
	},
},
![image](https://github.com/user-attachments/assets/b161cd9a-360d-4cad-969a-cceff9612d60)

**Comment by Zhuyi731** [comment]
[https://github.com/Zhuyi731/echarts-for-wx-uniapp/issues/23](相关issue)
