### ISSUE TITLE
支持canvas(2d)吗，我看原生的echarts那边支持了

### ISSUE THREAD

**Issue by yah0130** [Zhuyi731/echarts-for-wx-uniapp#5]

**Comment by yah0130** [comment]
好吧我自己照着改了需要pr吗

**Comment by Zhuyi731** [comment]
> 好吧我自己照着改了需要pr吗

可以呀，最新在忙其他的没时间关注这个项目，那麻烦你了

**Comment by yah0130** [comment]
> > 好吧我自己照着改了需要pr吗
> 
> 可以呀，最新在忙其他的没时间关注这个项目，那麻烦你了

提了个pr你看看

**Comment by Zhuyi731** [comment]
> > > 好吧我自己照着改了需要pr吗
> > 
> > 
> > 可以呀，最新在忙其他的没时间关注这个项目，那麻烦你了
> 
> 提了个pr你看看

已合并
